on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: unbuntu-latest


    steps: 
      - uses: actions/checkout@v3

      - name: "login to docker hub"
        run: docker login --username 3bod --password dckr_pat_hyNOs_qGfNZYrjjCI-rOHg5RSn8






