on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: unbuntu-latest


    steps: 
      - name: "testing github"
        run: pwd
      -name: "testing printing"
        run: echo Abod






