on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: unbuntu-latest


    steps: 
      - name: "testing github"
        run: pwd
      - name: "testing printing"
        run: echo Abod
      - name: "login to docker hub"
        run: docker login --username 3bod --password dckr_pat_hyNOs_qGfNZYrjjCI-rOHg5RSn8






